version: "3.8"
services:
  app:
    image: rental_hub:development
    build: ./
    volumes:
      - "./:/home/app"
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - REDIS_URL=${REDIS_URL} # auth cache
      - DATABASE_URL=${DATABASE_URL}
      - TZ=America/New_York
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USE_SSL=${MAIL_USE_SSL}
    tty: true

  cache:
    image: redis:alpine

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    

  client:
    image: rental_hub-client:development
    build: ./app/client
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - './app/client/app:/home/app'
      - '/home/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:5000/api
      - REACT_APP_SESSION_REFRESH_TTL=300

volumes:
  db-data: